apiVersion: apps/v1
kind: Deployment
metadata:
  name: url-shortener-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: url-shortener-auth
  template:
    metadata:
      labels:
        app: url-shortener-auth
    spec:
      containers:
      - name: url-shortener-auth
        image: url-shortener-auth:latest
        resources: {}
        ports:
            - containerPort: 8080
        env:
            - name: MONGO_URL
              value: mongodb://mongo-auth:27017/dev
            - name: RABBIT_HOST
              value: url-shortener-rabbitmq
        imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
    name: url-shortener-auth
spec:
    selector:
        app: url-shortener-auth
    ports:
        - port: 8080
          targetPort: 8080
    type: ClusterIP
