apiVersion: skaffold/v2beta12
kind: Config
metadata:
  name: backend
build:
  artifacts:
  - image: scys12/url-shortener-auth
    context: auth
    docker:
      dockerfile: Dockerfile
  - image: scys12/url-shortener-mail
    context: mail
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - k8s/auth-depl.yaml
    - k8s/mail-depl.yaml
    - k8s/mongo-depl.yaml
