app:
  security:
    jwtSecret: JWTSuperSecretKey
    jwtExpirationInMs: 604800000
spring:
  data:
    mongodb:
      uri: ${MONGO_URL:mongodb://localhost:27017/dev}
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: ${GOOGLE_CLIENT_ID}
            clientSecret: ${GOOGLE_CLIENT_SECRET}
            redirectUriTemplate: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile
server:
  servlet:
    context-path: /auth