app:
  security:
    jwtSecret: JWTSuperSecretKey
    jwtExpirationInMs: 604800000
  rabbitmq:
    exchange: urlshortener-auth.exchange
    queue: urlshortener-auth.queue
    routingkey: urlshortener-auth.routingkey

spring:
  data:
    mongodb:
      uri: ${MONGO_URL:mongodb://localhost:27017/dev}
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: ${GOOGLE_CLIENT_ID}
            clientSecret: ${GOOGLE_CLIENT_SECRET}
            redirectUriTemplate: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile
  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: 5672
    username: guest
    password: guest
server:
  servlet:
    context-path: /auth