apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: url-shortener-mail
  name: url-shortener-mail
spec:
  replicas: 1
  selector:
    matchLabels:
      app: url-shortener-mail
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: url-shortener-mail
    spec:
      containers:
      - name: url-shortener-mail
        image: scys12/url-shortener-mail:1.0.0
        resources: {}
        ports:
            - containerPort: 8081
        env:
            - name: RABBIT_HOST
              value: url-shortener-rabbitmq
        imagePullPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
    name: url-shortener-mail
spec:
    selector:
        app: url-shortener-mail
    ports:
        - port: 8081
          targetPort: 8081
    type: LoadBalancer
